function build_codegen_static_low_stack_bool()
% Generate a static-state C library with lower stack pressure.
%
% This profile keeps the current "source only" output behavior, but biases
% MATLAB Coder toward heap allocation for larger fixed-size work buffers.
% A moderate threshold keeps small helpers on stack while still moving the
% 150/300-sample work buffers away from task stack on Cortex-M targets.

build_ppg_codegen( ...
    'OutputDir', 'codegen_static_low_stack_bool', ...
    'MultiInstanceCode', false, ...
    'EnableOpenMP', false, ...
    'EnableAutoParallelization', false, ...
    'UseBuiltInCTypes', true, ...
    'EnableDynamicMemoryAllocation', true, ...
    'DynamicMemoryAllocationThreshold', 256, ...
    'DynamicMemoryAllocationForFixedSizeArrays', true, ...
    'GenCodeOnly', true, ...
    'GenerateMakefile', false, ...
    'GenerateExampleMain', 'GenerateCodeOnly', ...
    'ProdHWDeviceType', 'ARM Compatible->ARM Cortex-M', ...
    'GenerateReport', false);
end
