function build_codegen_static_no_openmp_bool()
% Generate a static-state C library without OpenMP and with built-in C types.

build_ppg_codegen( ...
    'OutputDir', 'codegen_static_no_openmp_bool', ...
    'MultiInstanceCode', false, ...
    'EnableOpenMP', false, ...
    'EnableAutoParallelization', false, ...
    'UseBuiltInCTypes', true, ...
    'EnableDynamicMemoryAllocation', true, ...
    'DynamicMemoryAllocationThreshold', 1280, ...
    'DynamicMemoryAllocationForFixedSizeArrays', false, ...
    'GenCodeOnly', true, ...
    'GenerateMakefile', false, ...
    'GenerateExampleMain', 'GenerateCodeOnly', ...
    'ProdHWDeviceType', 'ARM Compatible->ARM Cortex-M', ...
    'GenerateReport', false);
end
