function Spo2 = calculate_spo2_beat30_fitted(inputR)
% Auto-generated by R_SpO2_scatter_beat30_calibration.m
piecewiseCoeffs = [100.189675242280, -10.578951720575, 0.575188393182, -20.702560879960];
Spo2 = (inputR <= piecewiseCoeffs(3)).*(piecewiseCoeffs(1) + piecewiseCoeffs(2) * inputR) + ...
    (inputR > piecewiseCoeffs(3)).*(piecewiseCoeffs(1) + piecewiseCoeffs(2) * piecewiseCoeffs(3) + piecewiseCoeffs(4) * (inputR - piecewiseCoeffs(3)));
Spo2 = max(min(Spo2, 100), 65);
end
