function Spo2 = calculate_spo2_beat30_fitted(inputR)
% Auto-generated by R_SpO2_scatter_beat30_calibration.m
quadraticCoeffs = [-16.567031677626, -6.051443714005, 102.101206870292];
Spo2 = quadraticCoeffs(1) * inputR.^2 + quadraticCoeffs(2) * inputR + quadraticCoeffs(3);
Spo2 = max(min(Spo2, 100), 65);
end
